paths:
  exp_savepath: ./exp_results/cv
  model_savepath: None
  datasets_path: ./data

experiment:
  name: cifar10_simple_min_log_fixed_new

  mab_params:
    num_pulls: 100
    dataloader_cycled: True
    dataloader_iters: 50

    train_hyperparams:
        batch_size: 128
        lr: 1e-3
        device: "cuda:2"

  full_train_params:
      early_stop_epochs: 10
      early_stop_conf: 0.001
      epochs: 100
      lr: 1e-4
      batch_size: 64
      weight_decay: 1e-5

defaults:
  - dataset: mnist